### ISSUE TITLE
ERROR: Error: The incoming JSON object does not contain a client_email field

### ISSUE THREAD

**Issue by athenasaurav** [ayoisaiah/weather-bot#9]
Followed all the steps but my bot is not replying to messages. 

ERROR: Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (C:\Users\athen\Datascience\React\using pusher\pusher\node_modules\google-auth-library\build\src\auth\jwtclient.js:193:19)
    at GoogleAuth._cacheClientFromJSON (C:\Users\athen\Datascience\React\using pusher\pusher\node_modules\google-auth-library\build\src\auth\googleauth.js:313:16)
    at GoogleAuth.getClient (C:\Users\athen\Datascience\React\using pusher\pusher\node_modules\google-auth-library\build\src\auth\googleauth.js:494:22)
    at GrpcClient._getCredentials (C:\Users\athen\Datascience\React\using pusher\pusher\node_modules\google-gax\build\src\grpc.js:92:40)
    at GrpcClient.createStub (C:\Users\athen\Datascience\React\using pusher\pusher\node_modules\google-gax\build\src\grpc.js:213:34)
    at new SessionsClient (C:\Users\athen\Datascience\React\using pusher\pusher\node_modules\dialogflow\src\v2\sessions_client.js:159:34)
    **at Object.<anonymous> (C:\Users\athen\Datascience\React\using pusher\pusher\process-message.js:24:27)**
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)

**Comment by Clintjeez** [comment]
I got same error too please could you find a fix for it
